-- PHASE 4: Multi-Agent Cognitive Architecture Schema

-- 1. Agent Runs (The high-level execution session)
CREATE TABLE agent_runs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    conversation_id UUID REFERENCES conversations(id) ON DELETE CASCADE,
    goal TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('pending', 'running', 'completed', 'failed', 'paused')),
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);

-- 2. Agent Tasks (Subtasks generated by the Planner)
CREATE TABLE agent_tasks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    run_id UUID NOT NULL REFERENCES agent_runs(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    priority INTEGER DEFAULT 0,
    status TEXT NOT NULL CHECK (status IN ('pending', 'in_progress', 'completed', 'failed')),
    assigned_agent TEXT, -- e.g., 'executor', 'memory'
    dependencies UUID[] DEFAULT '{}',
    output JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);

-- 3. Execution Steps (Granular steps within a run)
CREATE TABLE execution_steps (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    run_id UUID NOT NULL REFERENCES agent_runs(id) ON DELETE CASCADE,
    task_id UUID REFERENCES agent_tasks(id) ON DELETE SET NULL,
    agent_name TEXT NOT NULL,
    step_type TEXT NOT NULL CHECK (step_type IN ('thought', 'action', 'observation', 'reflection', 'error')),
    content TEXT NOT NULL,
    tool_call JSONB,
    tool_output JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);

-- 4. Agent Memories (Shared cognitive state/short-term context)
CREATE TABLE agent_memories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    run_id UUID NOT NULL REFERENCES agent_runs(id) ON DELETE CASCADE,
    key TEXT NOT NULL,
    value JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    UNIQUE(run_id, key)
);

-- 5. Human Approval Requests
CREATE TABLE approval_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    run_id UUID NOT NULL REFERENCES agent_runs(id) ON DELETE CASCADE,
    step_id UUID REFERENCES execution_steps(id) ON DELETE CASCADE,
    action_type TEXT NOT NULL,
    action_data JSONB NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('pending', 'approved', 'rejected')),
    requester_agent TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    decided_at TIMESTAMP WITH TIME ZONE
);

-- Row Level Security
ALTER TABLE agent_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE execution_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_memories ENABLE ROW LEVEL SECURITY;
ALTER TABLE approval_requests ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Users can manage own agent runs" ON agent_runs FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage tasks of own runs" ON agent_tasks FOR ALL 
USING (EXISTS (SELECT 1 FROM agent_runs WHERE id = agent_tasks.run_id AND user_id = auth.uid()));
CREATE POLICY "Users can manage steps of own runs" ON execution_steps FOR ALL 
USING (EXISTS (SELECT 1 FROM agent_runs WHERE id = execution_steps.run_id AND user_id = auth.uid()));
CREATE POLICY "Users can manage memories of own runs" ON agent_memories FOR ALL 
USING (EXISTS (SELECT 1 FROM agent_runs WHERE id = agent_memories.run_id AND user_id = auth.uid()));
CREATE POLICY "Users can manage approval requests of own runs" ON approval_requests FOR ALL 
USING (EXISTS (SELECT 1 FROM agent_runs WHERE id = approval_requests.run_id AND user_id = auth.uid()));

-- Indexes
CREATE INDEX idx_agent_runs_user_id ON agent_runs(user_id);
CREATE INDEX idx_agent_tasks_run_id ON agent_tasks(run_id);
CREATE INDEX idx_execution_steps_run_id ON execution_steps(run_id);
CREATE INDEX idx_agent_memories_run_id ON agent_memories(run_id);
